package org.rhq.metrics.qe.tools.rhqmt.gui.utils;

import com.vaadin.server.ExternalResource;
import com.vaadin.server.Page;
import com.vaadin.server.Resource;

/**
 * Enables you to easily use the <a
 * href="http://fortawesome.github.io/Font-Awesome">FontAwesome</a> icon font to
 * easily embed scalable icons in any component that supports HTML content,
 * anywhere in said content. The icons are actually fonts, so the scale, and can
 * be colored, just as the rest of the text.
 * <p>
 * By default, {@link #load()} uses a CDN is used to host the font and CSS
 * "from the cloud", so you can very quickly get up-and-running. <br/>
 * For production, you might want to generate an optimized font w/o unused
 * icons, for instance using the <a href="http://icomoon.io/app/">IconMoon</a>
 * app. Deploy your icon-font (for instance in your theme) and point
 * {@link FontAwesome} to the CSS with {@link #load(Resource)}, e.g
 * <code>FontAwesome.load(new ThemeResource("font-awesome/css/font-awesome.min.css"));</code>
 * </p>
 * 
 * @see http://fortawesome.github.io/Font-Awesome
 * @see http://fortawesome.github.io/Font-Awesome/#license
 * @see http://icomoon.io
 * @see http://cdnjs.com
 * @author marc
 * 
 */
public class IonIconsCDN {

    public static final String CDN = "//code.ionicframework.com/ionicons/2.0.0/css/ionicons.min.css";

    public static void load() {
        load(new ExternalResource(CDN));
    }

    /**
     * Loads the FontAwesome CSS, and thus actual font, from the given location.
     * <p>
     * <code>
     * FontAwesome.load(new ThemeResource("font-awesome/css/font-awesome.min.css"));
     * </code>
     * </p>
     * 
     * @param fontAwesomeCss
     */
    public static void load(Resource fontAwesomeCss) {
        Page.getCurrent().getStyles().add(fontAwesomeCss);
    }

    /**
     * Icon variant; multiple can be used, but all combinations do not make
     * sense.
     * 
     * @author marc
     * 
     */
    public enum IconVariant {
        /**
         * A larger icon
         */
        SIZE_LARGE("icon-large"),
        /**
         * 2x sized icon
         */
        SIZE_2X("icon-2x"),
        /**
         * 3x sized icon
         */
        SIZE_3X("icon-3x"),
        /**
         * 4x sized icon
         */
        SIZE_4X("icon-4x"),
        /**
         * Spinning (animated) icon. Most useful with icons such as
         * {@link Icon#spinner}.
         */
        SPIN("icon-spin"),
        /**
         * Adds a border around the icon
         */
        BORDER("icon-border"),
        /**
         * For e.g for easy pull quotes or article graphics, with larger icons
         * next to text.
         */
        PULL_LEFT("pull-left"),
        /**
         * For e.g for easy pull quotes or article graphics, with larger icons
         * next to text.
         */
        PULL_RIGHT("pull-right");

        private final String stylename;

        IconVariant(String stylename) {
            this.stylename = stylename;
        }

        @Override
        public String toString() {
            return stylename;
        }
    }

    /**
     * Font-Awesome icon.
     * <p>
     * The basic {@link #toString()} will produce HTML representing the regular
     * icon.<br/>
     * For variants, {@link #variant(IconVariant...)} can be used with one or
     * more {@link IconVariant}s.<br/>
     * For custom cases, the stylename is available via {@link #stylename()}.
     * </p>
     * <p>
     * Remember to {@link FontAwesome#load()} (or
     * {@link FontAwesome#load(Resource)}) first.
     * </p>
     * 
     * @author marc
     * 
     */
    public enum Icon {
    	ALERT("&#XF101;"),
    	ALERT_CIRCLED("&#XF100;"),
    	ANDROID_ADD("&#XF2C7;"),
    	ANDROID_ADD_CIRCLE("&#XF359;"),
    	ANDROID_ALARM_CLOCK("&#XF35A;"),
    	ANDROID_ALERT("&#XF35B;"),
    	ANDROID_APPS("&#XF35C;"),
    	ANDROID_ARCHIVE("&#XF2C9;"),
    	ANDROID_ARROW_BACK("&#XF2CA;"),
    	ANDROID_ARROW_DOWN("&#XF35D;"),
    	ANDROID_ARROW_DROPDOWN("&#XF35F;"),
    	ANDROID_ARROW_DROPDOWN_CIRCLE("&#XF35E;"),
    	ANDROID_ARROW_DROPLEFT("&#XF361;"),
    	ANDROID_ARROW_DROPLEFT_CIRCLE("&#XF360;"),
    	ANDROID_ARROW_DROPRIGHT("&#XF363;"),
    	ANDROID_ARROW_DROPRIGHT_CIRCLE("&#XF362;"),
    	ANDROID_ARROW_DROPUP("&#XF365;"),
    	ANDROID_ARROW_DROPUP_CIRCLE("&#XF364;"),
    	ANDROID_ARROW_FORWARD("&#XF30F;"),
    	ANDROID_ARROW_UP("&#XF366;"),
    	ANDROID_ATTACH("&#XF367;"),
    	ANDROID_BAR("&#XF368;"),
    	ANDROID_BICYCLE("&#XF369;"),
    	ANDROID_BOAT("&#XF36A;"),
    	ANDROID_BOOKMARK("&#XF36B;"),
    	ANDROID_BULB("&#XF36C;"),
    	ANDROID_BUS("&#XF36D;"),
    	ANDROID_CALENDAR("&#XF2D1;"),
    	ANDROID_CALL("&#XF2D2;"),
    	ANDROID_CAMERA("&#XF2D3;"),
    	ANDROID_CANCEL("&#XF36E;"),
    	ANDROID_CAR("&#XF36F;"),
    	ANDROID_CART("&#XF370;"),
    	ANDROID_CHAT("&#XF2D4;"),
    	ANDROID_CHECKBOX("&#XF374;"),
    	ANDROID_CHECKBOX_BLANK("&#XF371;"),
    	ANDROID_CHECKBOX_OUTLINE("&#XF373;"),
    	ANDROID_CHECKBOX_OUTLINE_BLANK("&#XF372;"),
    	ANDROID_CHECKMARK_CIRCLE("&#XF375;"),
    	ANDROID_CLIPBOARD("&#XF376;"),
    	ANDROID_CLOSE("&#XF2D7;"),
    	ANDROID_CLOUD("&#XF37A;"),
    	ANDROID_CLOUD_CIRCLE("&#XF377;"),
    	ANDROID_CLOUD_DONE("&#XF378;"),
    	ANDROID_CLOUD_OUTLINE("&#XF379;"),
    	ANDROID_COLOR_PALETTE("&#XF37B;"),
    	ANDROID_COMPASS("&#XF37C;"),
    	ANDROID_CONTACT("&#XF2D8;"),
    	ANDROID_CONTACTS("&#XF2D9;"),
    	ANDROID_CONTRACT("&#XF37D;"),
    	ANDROID_CREATE("&#XF37E;"),
    	ANDROID_DELETE("&#XF37F;"),
    	ANDROID_DESKTOP("&#XF380;"),
    	ANDROID_DOCUMENT("&#XF381;"),
    	ANDROID_DONE("&#XF383;"),
    	ANDROID_DONE_ALL("&#XF382;"),
    	ANDROID_DOWNLOAD("&#XF2DD;"),
    	ANDROID_DRAFTS("&#XF384;"),
    	ANDROID_EXIT("&#XF385;"),
    	ANDROID_EXPAND("&#XF386;"),
    	ANDROID_FAVORITE("&#XF388;"),
    	ANDROID_FAVORITE_OUTLINE("&#XF387;"),
    	ANDROID_FILM("&#XF389;"),
    	ANDROID_FOLDER("&#XF2E0;"),
    	ANDROID_FOLDER_OPEN("&#XF38A;"),
    	ANDROID_FUNNEL("&#XF38B;"),
    	ANDROID_GLOBE("&#XF38C;"),
    	ANDROID_HAND("&#XF2E3;"),
    	ANDROID_HANGOUT("&#XF38D;"),
    	ANDROID_HAPPY("&#XF38E;"),
    	ANDROID_HOME("&#XF38F;"),
    	ANDROID_IMAGE("&#XF2E4;"),
    	ANDROID_LAPTOP("&#XF390;"),
    	ANDROID_LIST("&#XF391;"),
    	ANDROID_LOCATE("&#XF2E9;"),
    	ANDROID_LOCK("&#XF392;"),
    	ANDROID_MAIL("&#XF2EB;"),
    	ANDROID_MAP("&#XF393;"),
    	ANDROID_MENU("&#XF394;"),
    	ANDROID_MICROPHONE("&#XF2EC;"),
    	ANDROID_MICROPHONE_OFF("&#XF395;"),
    	ANDROID_MORE_HORIZONTAL("&#XF396;"),
    	ANDROID_MORE_VERTICAL("&#XF397;"),
    	ANDROID_NAVIGATE("&#XF398;"),
    	ANDROID_NOTIFICATIONS("&#XF39B;"),
    	ANDROID_NOTIFICATIONS_NONE("&#XF399;"),
    	ANDROID_NOTIFICATIONS_OFF("&#XF39A;"),
    	ANDROID_OPEN("&#XF39C;"),
    	ANDROID_OPTIONS("&#XF39D;"),
    	ANDROID_PEOPLE("&#XF39E;"),
    	ANDROID_PERSON("&#XF3A0;"),
    	ANDROID_PERSON_ADD("&#XF39F;"),
    	ANDROID_PHONE_LANDSCAPE("&#XF3A1;"),
    	ANDROID_PHONE_PORTRAIT("&#XF3A2;"),
    	ANDROID_PIN("&#XF3A3;"),
    	ANDROID_PLANE("&#XF3A4;"),
    	ANDROID_PLAYSTORE("&#XF2F0;"),
    	ANDROID_PRINT("&#XF3A5;"),
    	ANDROID_RADIO_BUTTON_OFF("&#XF3A6;"),
    	ANDROID_RADIO_BUTTON_ON("&#XF3A7;"),
    	ANDROID_REFRESH("&#XF3A8;"),
    	ANDROID_REMOVE("&#XF2F4;"),
    	ANDROID_REMOVE_CIRCLE("&#XF3A9;"),
    	ANDROID_RESTAURANT("&#XF3AA;"),
    	ANDROID_SAD("&#XF3AB;"),
    	ANDROID_SEARCH("&#XF2F5;"),
    	ANDROID_SEND("&#XF2F6;"),
    	ANDROID_SETTINGS("&#XF2F7;"),
    	ANDROID_SHARE("&#XF2F8;"),
    	ANDROID_SHARE_ALT("&#XF3AC;"),
    	ANDROID_STAR("&#XF2FC;"),
    	ANDROID_STAR_HALF("&#XF3AD;"),
    	ANDROID_STAR_OUTLINE("&#XF3AE;"),
    	ANDROID_STOPWATCH("&#XF2FD;"),
    	ANDROID_SUBWAY("&#XF3AF;"),
    	ANDROID_SUNNY("&#XF3B0;"),
    	ANDROID_SYNC("&#XF3B1;"),
    	ANDROID_TEXTSMS("&#XF3B2;"),
    	ANDROID_TIME("&#XF3B3;"),
    	ANDROID_TRAIN("&#XF3B4;"),
    	ANDROID_UNLOCK("&#XF3B5;"),
    	ANDROID_UPLOAD("&#XF3B6;"),
    	ANDROID_VOLUME_DOWN("&#XF3B7;"),
    	ANDROID_VOLUME_MUTE("&#XF3B8;"),
    	ANDROID_VOLUME_OFF("&#XF3B9;"),
    	ANDROID_VOLUME_UP("&#XF3BA;"),
    	ANDROID_WALK("&#XF3BB;"),
    	ANDROID_WARNING("&#XF3BC;"),
    	ANDROID_WATCH("&#XF3BD;"),
    	ANDROID_WIFI("&#XF305;"),
    	APERTURE("&#XF313;"),
    	ARCHIVE("&#XF102;"),
    	ARROW_DOWN_A("&#XF103;"),
    	ARROW_DOWN_B("&#XF104;"),
    	ARROW_DOWN_C("&#XF105;"),
    	ARROW_EXPAND("&#XF25E;"),
    	ARROW_GRAPH_DOWN_LEFT("&#XF25F;"),
    	ARROW_GRAPH_DOWN_RIGHT("&#XF260;"),
    	ARROW_GRAPH_UP_LEFT("&#XF261;"),
    	ARROW_GRAPH_UP_RIGHT("&#XF262;"),
    	ARROW_LEFT_A("&#XF106;"),
    	ARROW_LEFT_B("&#XF107;"),
    	ARROW_LEFT_C("&#XF108;"),
    	ARROW_MOVE("&#XF263;"),
    	ARROW_RESIZE("&#XF264;"),
    	ARROW_RETURN_LEFT("&#XF265;"),
    	ARROW_RETURN_RIGHT("&#XF266;"),
    	ARROW_RIGHT_A("&#XF109;"),
    	ARROW_RIGHT_B("&#XF10A;"),
    	ARROW_RIGHT_C("&#XF10B;"),
    	ARROW_SHRINK("&#XF267;"),
    	ARROW_SWAP("&#XF268;"),
    	ARROW_UP_A("&#XF10C;"),
    	ARROW_UP_B("&#XF10D;"),
    	ARROW_UP_C("&#XF10E;"),
    	ASTERISK("&#XF314;"),
    	AT("&#XF10F;"),
    	BACKSPACE("&#XF3BF;"),
    	BACKSPACE_OUTLINE("&#XF3BE;"),
    	BAG("&#XF110;"),
    	BATTERY_CHARGING("&#XF111;"),
    	BATTERY_EMPTY("&#XF112;"),
    	BATTERY_FULL("&#XF113;"),
    	BATTERY_HALF("&#XF114;"),
    	BATTERY_LOW("&#XF115;"),
    	BEAKER("&#XF269;"),
    	BEER("&#XF26A;"),
    	BLUETOOTH("&#XF116;"),
    	BONFIRE("&#XF315;"),
    	BOOKMARK("&#XF26B;"),
    	BOWTIE("&#XF3C0;"),
    	BRIEFCASE("&#XF26C;"),
    	BUG("&#XF2BE;"),
    	CALCULATOR("&#XF26D;"),
    	CALENDAR("&#XF117;"),
    	CAMERA("&#XF118;"),
    	CARD("&#XF119;"),
    	CASH("&#XF316;"),
    	CHATBOX("&#XF11B;"),
    	CHATBOX_WORKING("&#XF11A;"),
    	CHATBOXES("&#XF11C;"),
    	CHATBUBBLE("&#XF11E;"),
    	CHATBUBBLE_WORKING("&#XF11D;"),
    	CHATBUBBLES("&#XF11F;"),
    	CHECKMARK("&#XF122;"),
    	CHECKMARK_CIRCLED("&#XF120;"),
    	CHECKMARK_ROUND("&#XF121;"),
    	CHEVRON_DOWN("&#XF123;"),
    	CHEVRON_LEFT("&#XF124;"),
    	CHEVRON_RIGHT("&#XF125;"),
    	CHEVRON_UP("&#XF126;"),
    	CLIPBOARD("&#XF127;"),
    	CLOCK("&#XF26E;"),
    	CLOSE("&#XF12A;"),
    	CLOSE_CIRCLED("&#XF128;"),
    	CLOSE_ROUND("&#XF129;"),
    	CLOSED_CAPTIONING("&#XF317;"),
    	CLOUD("&#XF12B;"),
    	CODE("&#XF271;"),
    	CODE_DOWNLOAD("&#XF26F;"),
    	CODE_WORKING("&#XF270;"),
    	COFFEE("&#XF272;"),
    	COMPASS("&#XF273;"),
    	COMPOSE("&#XF12C;"),
    	CONNECTION_BARS("&#XF274;"),
    	CONTRAST("&#XF275;"),
    	CROP("&#XF3C1;"),
    	CUBE("&#XF318;"),
    	DISC("&#XF12D;"),
    	DOCUMENT("&#XF12F;"),
    	DOCUMENT_TEXT("&#XF12E;"),
    	DRAG("&#XF130;"),
    	EARTH("&#XF276;"),
    	EASEL("&#XF3C2;"),
    	EDIT("&#XF2BF;"),
    	EGG("&#XF277;"),
    	EJECT("&#XF131;"),
    	EMAIL("&#XF132;"),
    	EMAIL_UNREAD("&#XF3C3;"),
    	ERLENMEYER_FLASK("&#XF3C5;"),
    	ERLENMEYER_FLASK_BUBBLES("&#XF3C4;"),
    	EYE("&#XF133;"),
    	EYE_DISABLED("&#XF306;"),
    	FEMALE("&#XF278;"),
    	FILING("&#XF134;"),
    	FILM_MARKER("&#XF135;"),
    	FIREBALL("&#XF319;"),
    	FLAG("&#XF279;"),
    	FLAME("&#XF31A;"),
    	FLASH("&#XF137;"),
    	FLASH_OFF("&#XF136;"),
    	FOLDER("&#XF139;"),
    	FORK("&#XF27A;"),
    	FORK_REPO("&#XF2C0;"),
    	FORWARD("&#XF13A;"),
    	FUNNEL("&#XF31B;"),
    	GEAR_A("&#XF13D;"),
    	GEAR_B("&#XF13E;"),
    	GRID("&#XF13F;"),
    	HAMMER("&#XF27B;"),
    	HAPPY("&#XF31C;"),
    	HAPPY_OUTLINE("&#XF3C6;"),
    	HEADPHONE("&#XF140;"),
    	HEART("&#XF141;"),
    	HEART_BROKEN("&#XF31D;"),
    	HELP("&#XF143;"),
    	HELP_BUOY("&#XF27C;"),
    	HELP_CIRCLED("&#XF142;"),
    	HOME("&#XF144;"),
    	ICECREAM("&#XF27D;"),
    	IMAGE("&#XF147;"),
    	IMAGES("&#XF148;"),
    	INFORMATION("&#XF14A;"),
    	INFORMATION_CIRCLED("&#XF149;"),
    	IONIC("&#XF14B;"),
    	IOS_ALARM("&#XF3C8;"),
    	IOS_ALARM_OUTLINE("&#XF3C7;"),
    	IOS_ALBUMS("&#XF3CA;"),
    	IOS_ALBUMS_OUTLINE("&#XF3C9;"),
    	IOS_AMERICANFOOTBALL("&#XF3CC;"),
    	IOS_AMERICANFOOTBALL_OUTLINE("&#XF3CB;"),
    	IOS_ANALYTICS("&#XF3CE;"),
    	IOS_ANALYTICS_OUTLINE("&#XF3CD;"),
    	IOS_ARROW_BACK("&#XF3CF;"),
    	IOS_ARROW_DOWN("&#XF3D0;"),
    	IOS_ARROW_FORWARD("&#XF3D1;"),
    	IOS_ARROW_LEFT("&#XF3D2;"),
    	IOS_ARROW_RIGHT("&#XF3D3;"),
    	IOS_ARROW_THIN_DOWN("&#XF3D4;"),
    	IOS_ARROW_THIN_LEFT("&#XF3D5;"),
    	IOS_ARROW_THIN_RIGHT("&#XF3D6;"),
    	IOS_ARROW_THIN_UP("&#XF3D7;"),
    	IOS_ARROW_UP("&#XF3D8;"),
    	IOS_AT("&#XF3DA;"),
    	IOS_AT_OUTLINE("&#XF3D9;"),
    	IOS_BARCODE("&#XF3DC;"),
    	IOS_BARCODE_OUTLINE("&#XF3DB;"),
    	IOS_BASEBALL("&#XF3DE;"),
    	IOS_BASEBALL_OUTLINE("&#XF3DD;"),
    	IOS_BASKETBALL("&#XF3E0;"),
    	IOS_BASKETBALL_OUTLINE("&#XF3DF;"),
    	IOS_BELL("&#XF3E2;"),
    	IOS_BELL_OUTLINE("&#XF3E1;"),
    	IOS_BODY("&#XF3E4;"),
    	IOS_BODY_OUTLINE("&#XF3E3;"),
    	IOS_BOLT("&#XF3E6;"),
    	IOS_BOLT_OUTLINE("&#XF3E5;"),
    	IOS_BOOK("&#XF3E8;"),
    	IOS_BOOK_OUTLINE("&#XF3E7;"),
    	IOS_BOOKMARKS("&#XF3EA;"),
    	IOS_BOOKMARKS_OUTLINE("&#XF3E9;"),
    	IOS_BOX("&#XF3EC;"),
    	IOS_BOX_OUTLINE("&#XF3EB;"),
    	IOS_BRIEFCASE("&#XF3EE;"),
    	IOS_BRIEFCASE_OUTLINE("&#XF3ED;"),
    	IOS_BROWSERS("&#XF3F0;"),
    	IOS_BROWSERS_OUTLINE("&#XF3EF;"),
    	IOS_CALCULATOR("&#XF3F2;"),
    	IOS_CALCULATOR_OUTLINE("&#XF3F1;"),
    	IOS_CALENDAR("&#XF3F4;"),
    	IOS_CALENDAR_OUTLINE("&#XF3F3;"),
    	IOS_CAMERA("&#XF3F6;"),
    	IOS_CAMERA_OUTLINE("&#XF3F5;"),
    	IOS_CART("&#XF3F8;"),
    	IOS_CART_OUTLINE("&#XF3F7;"),
    	IOS_CHATBOXES("&#XF3FA;"),
    	IOS_CHATBOXES_OUTLINE("&#XF3F9;"),
    	IOS_CHATBUBBLE("&#XF3FC;"),
    	IOS_CHATBUBBLE_OUTLINE("&#XF3FB;"),
    	IOS_CHECKMARK("&#XF3FF;"),
    	IOS_CHECKMARK_EMPTY("&#XF3FD;"),
    	IOS_CHECKMARK_OUTLINE("&#XF3FE;"),
    	IOS_CIRCLE_FILLED("&#XF400;"),
    	IOS_CIRCLE_OUTLINE("&#XF401;"),
    	IOS_CLOCK("&#XF403;"),
    	IOS_CLOCK_OUTLINE("&#XF402;"),
    	IOS_CLOSE("&#XF406;"),
    	IOS_CLOSE_EMPTY("&#XF404;"),
    	IOS_CLOSE_OUTLINE("&#XF405;"),
    	IOS_CLOUD("&#XF40C;"),
    	IOS_CLOUD_DOWNLOAD("&#XF408;"),
    	IOS_CLOUD_DOWNLOAD_OUTLINE("&#XF407;"),
    	IOS_CLOUD_OUTLINE("&#XF409;"),
    	IOS_CLOUD_UPLOAD("&#XF40B;"),
    	IOS_CLOUD_UPLOAD_OUTLINE("&#XF40A;"),
    	IOS_CLOUDY("&#XF410;"),
    	IOS_CLOUDY_NIGHT("&#XF40E;"),
    	IOS_CLOUDY_NIGHT_OUTLINE("&#XF40D;"),
    	IOS_CLOUDY_OUTLINE("&#XF40F;"),
    	IOS_COG("&#XF412;"),
    	IOS_COG_OUTLINE("&#XF411;"),
    	IOS_COLOR_FILTER("&#XF414;"),
    	IOS_COLOR_FILTER_OUTLINE("&#XF413;"),
    	IOS_COLOR_WAND("&#XF416;"),
    	IOS_COLOR_WAND_OUTLINE("&#XF415;"),
    	IOS_COMPOSE("&#XF418;"),
    	IOS_COMPOSE_OUTLINE("&#XF417;"),
    	IOS_CONTACT("&#XF41A;"),
    	IOS_CONTACT_OUTLINE("&#XF419;"),
    	IOS_COPY("&#XF41C;"),
    	IOS_COPY_OUTLINE("&#XF41B;"),
    	IOS_CROP("&#XF41E;"),
    	IOS_CROP_STRONG("&#XF41D;"),
    	IOS_DOWNLOAD("&#XF420;"),
    	IOS_DOWNLOAD_OUTLINE("&#XF41F;"),
    	IOS_DRAG("&#XF421;"),
    	IOS_EMAIL("&#XF423;"),
    	IOS_EMAIL_OUTLINE("&#XF422;"),
    	IOS_EYE("&#XF425;"),
    	IOS_EYE_OUTLINE("&#XF424;"),
    	IOS_FASTFORWARD("&#XF427;"),
    	IOS_FASTFORWARD_OUTLINE("&#XF426;"),
    	IOS_FILING("&#XF429;"),
    	IOS_FILING_OUTLINE("&#XF428;"),
    	IOS_FILM("&#XF42B;"),
    	IOS_FILM_OUTLINE("&#XF42A;"),
    	IOS_FLAG("&#XF42D;"),
    	IOS_FLAG_OUTLINE("&#XF42C;"),
    	IOS_FLAME("&#XF42F;"),
    	IOS_FLAME_OUTLINE("&#XF42E;"),
    	IOS_FLASK("&#XF431;"),
    	IOS_FLASK_OUTLINE("&#XF430;"),
    	IOS_FLOWER("&#XF433;"),
    	IOS_FLOWER_OUTLINE("&#XF432;"),
    	IOS_FOLDER("&#XF435;"),
    	IOS_FOLDER_OUTLINE("&#XF434;"),
    	IOS_FOOTBALL("&#XF437;"),
    	IOS_FOOTBALL_OUTLINE("&#XF436;"),
    	IOS_GAME_CONTROLLER_A("&#XF439;"),
    	IOS_GAME_CONTROLLER_A_OUTLINE("&#XF438;"),
    	IOS_GAME_CONTROLLER_B("&#XF43B;"),
    	IOS_GAME_CONTROLLER_B_OUTLINE("&#XF43A;"),
    	IOS_GEAR("&#XF43D;"),
    	IOS_GEAR_OUTLINE("&#XF43C;"),
    	IOS_GLASSES("&#XF43F;"),
    	IOS_GLASSES_OUTLINE("&#XF43E;"),
    	IOS_GRID_VIEW("&#XF441;"),
    	IOS_GRID_VIEW_OUTLINE("&#XF440;"),
    	IOS_HEART("&#XF443;"),
    	IOS_HEART_OUTLINE("&#XF442;"),
    	IOS_HELP("&#XF446;"),
    	IOS_HELP_EMPTY("&#XF444;"),
    	IOS_HELP_OUTLINE("&#XF445;"),
    	IOS_HOME("&#XF448;"),
    	IOS_HOME_OUTLINE("&#XF447;"),
    	IOS_INFINITE("&#XF44A;"),
    	IOS_INFINITE_OUTLINE("&#XF449;"),
    	IOS_INFORMATION("&#XF44D;"),
    	IOS_INFORMATION_EMPTY("&#XF44B;"),
    	IOS_INFORMATION_OUTLINE("&#XF44C;"),
    	IOS_IONIC_OUTLINE("&#XF44E;"),
    	IOS_KEYPAD("&#XF450;"),
    	IOS_KEYPAD_OUTLINE("&#XF44F;"),
    	IOS_LIGHTBULB("&#XF452;"),
    	IOS_LIGHTBULB_OUTLINE("&#XF451;"),
    	IOS_LIST("&#XF454;"),
    	IOS_LIST_OUTLINE("&#XF453;"),
    	IOS_LOCATION("&#XF456;"),
    	IOS_LOCATION_OUTLINE("&#XF455;"),
    	IOS_LOCKED("&#XF458;"),
    	IOS_LOCKED_OUTLINE("&#XF457;"),
    	IOS_LOOP("&#XF45A;"),
    	IOS_LOOP_STRONG("&#XF459;"),
    	IOS_MEDICAL("&#XF45C;"),
    	IOS_MEDICAL_OUTLINE("&#XF45B;"),
    	IOS_MEDKIT("&#XF45E;"),
    	IOS_MEDKIT_OUTLINE("&#XF45D;"),
    	IOS_MIC("&#XF461;"),
    	IOS_MIC_OFF("&#XF45F;"),
    	IOS_MIC_OUTLINE("&#XF460;"),
    	IOS_MINUS("&#XF464;"),
    	IOS_MINUS_EMPTY("&#XF462;"),
    	IOS_MINUS_OUTLINE("&#XF463;"),
    	IOS_MONITOR("&#XF466;"),
    	IOS_MONITOR_OUTLINE("&#XF465;"),
    	IOS_MOON("&#XF468;"),
    	IOS_MOON_OUTLINE("&#XF467;"),
    	IOS_MORE("&#XF46A;"),
    	IOS_MORE_OUTLINE("&#XF469;"),
    	IOS_MUSICAL_NOTE("&#XF46B;"),
    	IOS_MUSICAL_NOTES("&#XF46C;"),
    	IOS_NAVIGATE("&#XF46E;"),
    	IOS_NAVIGATE_OUTLINE("&#XF46D;"),
    	IOS_NUTRITION("&#XF470;"),
    	IOS_NUTRITION_OUTLINE("&#XF46F;"),
    	IOS_PAPER("&#XF472;"),
    	IOS_PAPER_OUTLINE("&#XF471;"),
    	IOS_PAPERPLANE("&#XF474;"),
    	IOS_PAPERPLANE_OUTLINE("&#XF473;"),
    	IOS_PARTLYSUNNY("&#XF476;"),
    	IOS_PARTLYSUNNY_OUTLINE("&#XF475;"),
    	IOS_PAUSE("&#XF478;"),
    	IOS_PAUSE_OUTLINE("&#XF477;"),
    	IOS_PAW("&#XF47A;"),
    	IOS_PAW_OUTLINE("&#XF479;"),
    	IOS_PEOPLE("&#XF47C;"),
    	IOS_PEOPLE_OUTLINE("&#XF47B;"),
    	IOS_PERSON("&#XF47E;"),
    	IOS_PERSON_OUTLINE("&#XF47D;"),
    	IOS_PERSONADD("&#XF480;"),
    	IOS_PERSONADD_OUTLINE("&#XF47F;"),
    	IOS_PHOTOS("&#XF482;"),
    	IOS_PHOTOS_OUTLINE("&#XF481;"),
    	IOS_PIE("&#XF484;"),
    	IOS_PIE_OUTLINE("&#XF483;"),
    	IOS_PINT("&#XF486;"),
    	IOS_PINT_OUTLINE("&#XF485;"),
    	IOS_PLAY("&#XF488;"),
    	IOS_PLAY_OUTLINE("&#XF487;"),
    	IOS_PLUS("&#XF48B;"),
    	IOS_PLUS_EMPTY("&#XF489;"),
    	IOS_PLUS_OUTLINE("&#XF48A;"),
    	IOS_PRICETAG("&#XF48D;"),
    	IOS_PRICETAG_OUTLINE("&#XF48C;"),
    	IOS_PRICETAGS("&#XF48F;"),
    	IOS_PRICETAGS_OUTLINE("&#XF48E;"),
    	IOS_PRINTER("&#XF491;"),
    	IOS_PRINTER_OUTLINE("&#XF490;"),
    	IOS_PULSE("&#XF493;"),
    	IOS_PULSE_STRONG("&#XF492;"),
    	IOS_RAINY("&#XF495;"),
    	IOS_RAINY_OUTLINE("&#XF494;"),
    	IOS_RECORDING("&#XF497;"),
    	IOS_RECORDING_OUTLINE("&#XF496;"),
    	IOS_REDO("&#XF499;"),
    	IOS_REDO_OUTLINE("&#XF498;"),
    	IOS_REFRESH("&#XF49C;"),
    	IOS_REFRESH_EMPTY("&#XF49A;"),
    	IOS_REFRESH_OUTLINE("&#XF49B;"),
    	IOS_RELOAD("&#XF49D;"),
    	IOS_REVERSE_CAMERA("&#XF49F;"),
    	IOS_REVERSE_CAMERA_OUTLINE("&#XF49E;"),
    	IOS_REWIND("&#XF4A1;"),
    	IOS_REWIND_OUTLINE("&#XF4A0;"),
    	IOS_ROSE("&#XF4A3;"),
    	IOS_ROSE_OUTLINE("&#XF4A2;"),
    	IOS_SEARCH("&#XF4A5;"),
    	IOS_SEARCH_STRONG("&#XF4A4;"),
    	IOS_SETTINGS("&#XF4A7;"),
    	IOS_SETTINGS_STRONG("&#XF4A6;"),
    	IOS_SHUFFLE("&#XF4A9;"),
    	IOS_SHUFFLE_STRONG("&#XF4A8;"),
    	IOS_SKIPBACKWARD("&#XF4AB;"),
    	IOS_SKIPBACKWARD_OUTLINE("&#XF4AA;"),
    	IOS_SKIPFORWARD("&#XF4AD;"),
    	IOS_SKIPFORWARD_OUTLINE("&#XF4AC;"),
    	IOS_SNOWY("&#XF4AE;"),
    	IOS_SPEEDOMETER("&#XF4B0;"),
    	IOS_SPEEDOMETER_OUTLINE("&#XF4AF;"),
    	IOS_STAR("&#XF4B3;"),
    	IOS_STAR_HALF("&#XF4B1;"),
    	IOS_STAR_OUTLINE("&#XF4B2;"),
    	IOS_STOPWATCH("&#XF4B5;"),
    	IOS_STOPWATCH_OUTLINE("&#XF4B4;"),
    	IOS_SUNNY("&#XF4B7;"),
    	IOS_SUNNY_OUTLINE("&#XF4B6;"),
    	IOS_TELEPHONE("&#XF4B9;"),
    	IOS_TELEPHONE_OUTLINE("&#XF4B8;"),
    	IOS_TENNISBALL("&#XF4BB;"),
    	IOS_TENNISBALL_OUTLINE("&#XF4BA;"),
    	IOS_THUNDERSTORM("&#XF4BD;"),
    	IOS_THUNDERSTORM_OUTLINE("&#XF4BC;"),
    	IOS_TIME("&#XF4BF;"),
    	IOS_TIME_OUTLINE("&#XF4BE;"),
    	IOS_TIMER("&#XF4C1;"),
    	IOS_TIMER_OUTLINE("&#XF4C0;"),
    	IOS_TOGGLE("&#XF4C3;"),
    	IOS_TOGGLE_OUTLINE("&#XF4C2;"),
    	IOS_TRASH("&#XF4C5;"),
    	IOS_TRASH_OUTLINE("&#XF4C4;"),
    	IOS_UNDO("&#XF4C7;"),
    	IOS_UNDO_OUTLINE("&#XF4C6;"),
    	IOS_UNLOCKED("&#XF4C9;"),
    	IOS_UNLOCKED_OUTLINE("&#XF4C8;"),
    	IOS_UPLOAD("&#XF4CB;"),
    	IOS_UPLOAD_OUTLINE("&#XF4CA;"),
    	IOS_VIDEOCAM("&#XF4CD;"),
    	IOS_VIDEOCAM_OUTLINE("&#XF4CC;"),
    	IOS_VOLUME_HIGH("&#XF4CE;"),
    	IOS_VOLUME_LOW("&#XF4CF;"),
    	IOS_WINEGLASS("&#XF4D1;"),
    	IOS_WINEGLASS_OUTLINE("&#XF4D0;"),
    	IOS_WORLD("&#XF4D3;"),
    	IOS_WORLD_OUTLINE("&#XF4D2;"),
    	IPAD("&#XF1F9;"),
    	IPHONE("&#XF1FA;"),
    	IPOD("&#XF1FB;"),
    	JET("&#XF295;"),
    	KEY("&#XF296;"),
    	KNIFE("&#XF297;"),
    	LAPTOP("&#XF1FC;"),
    	LEAF("&#XF1FD;"),
    	LEVELS("&#XF298;"),
    	LIGHTBULB("&#XF299;"),
    	LINK("&#XF1FE;"),
    	LOAD_A("&#XF29A;"),
    	LOAD_B("&#XF29B;"),
    	LOAD_C("&#XF29C;"),
    	LOAD_D("&#XF29D;"),
    	LOCATION("&#XF1FF;"),
    	LOCK_COMBINATION("&#XF4D4;"),
    	LOCKED("&#XF200;"),
    	LOG_IN("&#XF29E;"),
    	LOG_OUT("&#XF29F;"),
    	LOOP("&#XF201;"),
    	MAGNET("&#XF2A0;"),
    	MALE("&#XF2A1;"),
    	MAN("&#XF202;"),
    	MAP("&#XF203;"),
    	MEDKIT("&#XF2A2;"),
    	MERGE("&#XF33F;"),
    	MIC_A("&#XF204;"),
    	MIC_B("&#XF205;"),
    	MIC_C("&#XF206;"),
    	MINUS("&#XF209;"),
    	MINUS_CIRCLED("&#XF207;"),
    	MINUS_ROUND("&#XF208;"),
    	MODEL_S("&#XF2C1;"),
    	MONITOR("&#XF20A;"),
    	MORE("&#XF20B;"),
    	MOUSE("&#XF340;"),
    	MUSIC_NOTE("&#XF20C;"),
    	NAVICON("&#XF20E;"),
    	NAVICON_ROUND("&#XF20D;"),
    	NAVIGATE("&#XF2A3;"),
    	NETWORK("&#XF341;"),
    	NO_SMOKING("&#XF2C2;"),
    	NUCLEAR("&#XF2A4;"),
    	OUTLET("&#XF342;"),
    	PAINTBRUSH("&#XF4D5;"),
    	PAINTBUCKET("&#XF4D6;"),
    	PAPER_AIRPLANE("&#XF2C3;"),
    	PAPERCLIP("&#XF20F;"),
    	PAUSE("&#XF210;"),
    	PERSON("&#XF213;"),
    	PERSON_ADD("&#XF211;"),
    	PERSON_STALKER("&#XF212;"),
    	PIE_GRAPH("&#XF2A5;"),
    	PIN("&#XF2A6;"),
    	PINPOINT("&#XF2A7;"),
    	PIZZA("&#XF2A8;"),
    	PLANE("&#XF214;"),
    	PLANET("&#XF343;"),
    	PLAY("&#XF215;"),
    	PLAYSTATION("&#XF30A;"),
    	PLUS("&#XF218;"),
    	PLUS_CIRCLED("&#XF216;"),
    	PLUS_ROUND("&#XF217;"),
    	PODIUM("&#XF344;"),
    	POUND("&#XF219;"),
    	POWER("&#XF2A9;"),
    	PRICETAG("&#XF2AA;"),
    	PRICETAGS("&#XF2AB;"),
    	PRINTER("&#XF21A;"),
    	PULL_REQUEST("&#XF345;"),
    	QR_SCANNER("&#XF346;"),
    	QUOTE("&#XF347;"),
    	RADIO_WAVES("&#XF2AC;"),
    	RECORD("&#XF21B;"),
    	REFRESH("&#XF21C;"),
    	REPLY("&#XF21E;"),
    	REPLY_ALL("&#XF21D;"),
    	RIBBON_A("&#XF348;"),
    	RIBBON_B("&#XF349;"),
    	SAD("&#XF34A;"),
    	SAD_OUTLINE("&#XF4D7;"),
    	SCISSORS("&#XF34B;"),
    	SEARCH("&#XF21F;"),
    	SETTINGS("&#XF2AD;"),
    	SHARE("&#XF220;"),
    	SHUFFLE("&#XF221;"),
    	SKIP_BACKWARD("&#XF222;"),
    	SKIP_FORWARD("&#XF223;"),
    	SOCIAL_ANDROID("&#XF225;"),
    	SOCIAL_ANDROID_OUTLINE("&#XF224;"),
    	SOCIAL_ANGULAR("&#XF4D9;"),
    	SOCIAL_ANGULAR_OUTLINE("&#XF4D8;"),
    	SOCIAL_APPLE("&#XF227;"),
    	SOCIAL_APPLE_OUTLINE("&#XF226;"),
    	SOCIAL_BITCOIN("&#XF2AF;"),
    	SOCIAL_BITCOIN_OUTLINE("&#XF2AE;"),
    	SOCIAL_BUFFER("&#XF229;"),
    	SOCIAL_BUFFER_OUTLINE("&#XF228;"),
    	SOCIAL_CHROME("&#XF4DB;"),
    	SOCIAL_CHROME_OUTLINE("&#XF4DA;"),
    	SOCIAL_CODEPEN("&#XF4DD;"),
    	SOCIAL_CODEPEN_OUTLINE("&#XF4DC;"),
    	SOCIAL_CSS3("&#XF4DF;"),
    	SOCIAL_CSS3_OUTLINE("&#XF4DE;"),
    	SOCIAL_DESIGNERNEWS("&#XF22B;"),
    	SOCIAL_DESIGNERNEWS_OUTLINE("&#XF22A;"),
    	SOCIAL_DRIBBBLE("&#XF22D;"),
    	SOCIAL_DRIBBBLE_OUTLINE("&#XF22C;"),
    	SOCIAL_DROPBOX("&#XF22F;"),
    	SOCIAL_DROPBOX_OUTLINE("&#XF22E;"),
    	SOCIAL_EURO("&#XF4E1;"),
    	SOCIAL_EURO_OUTLINE("&#XF4E0;"),
    	SOCIAL_FACEBOOK("&#XF231;"),
    	SOCIAL_FACEBOOK_OUTLINE("&#XF230;"),
    	SOCIAL_FOURSQUARE("&#XF34D;"),
    	SOCIAL_FOURSQUARE_OUTLINE("&#XF34C;"),
    	SOCIAL_FREEBSD_DEVIL("&#XF2C4;"),
    	SOCIAL_GITHUB("&#XF233;"),
    	SOCIAL_GITHUB_OUTLINE("&#XF232;"),
    	SOCIAL_GOOGLE("&#XF34F;"),
    	SOCIAL_GOOGLE_OUTLINE("&#XF34E;"),
    	SOCIAL_GOOGLEPLUS("&#XF235;"),
    	SOCIAL_GOOGLEPLUS_OUTLINE("&#XF234;"),
    	SOCIAL_HACKERNEWS("&#XF237;"),
    	SOCIAL_HACKERNEWS_OUTLINE("&#XF236;"),
    	SOCIAL_HTML5("&#XF4E3;"),
    	SOCIAL_HTML5_OUTLINE("&#XF4E2;"),
    	SOCIAL_INSTAGRAM("&#XF351;"),
    	SOCIAL_INSTAGRAM_OUTLINE("&#XF350;"),
    	SOCIAL_JAVASCRIPT("&#XF4E5;"),
    	SOCIAL_JAVASCRIPT_OUTLINE("&#XF4E4;"),
    	SOCIAL_LINKEDIN("&#XF239;"),
    	SOCIAL_LINKEDIN_OUTLINE("&#XF238;"),
    	SOCIAL_MARKDOWN("&#XF4E6;"),
    	SOCIAL_NODEJS("&#XF4E7;"),
    	SOCIAL_OCTOCAT("&#XF4E8;"),
    	SOCIAL_PINTEREST("&#XF2B1;"),
    	SOCIAL_PINTEREST_OUTLINE("&#XF2B0;"),
    	SOCIAL_PYTHON("&#XF4E9;"),
    	SOCIAL_REDDIT("&#XF23B;"),
    	SOCIAL_REDDIT_OUTLINE("&#XF23A;"),
    	SOCIAL_RSS("&#XF23D;"),
    	SOCIAL_RSS_OUTLINE("&#XF23C;"),
    	SOCIAL_SASS("&#XF4EA;"),
    	SOCIAL_SKYPE("&#XF23F;"),
    	SOCIAL_SKYPE_OUTLINE("&#XF23E;"),
    	SOCIAL_SNAPCHAT("&#XF4EC;"),
    	SOCIAL_SNAPCHAT_OUTLINE("&#XF4EB;"),
    	SOCIAL_TUMBLR("&#XF241;"),
    	SOCIAL_TUMBLR_OUTLINE("&#XF240;"),
    	SOCIAL_TUX("&#XF2C5;"),
    	SOCIAL_TWITCH("&#XF4EE;"),
    	SOCIAL_TWITCH_OUTLINE("&#XF4ED;"),
    	SOCIAL_TWITTER("&#XF243;"),
    	SOCIAL_TWITTER_OUTLINE("&#XF242;"),
    	SOCIAL_USD("&#XF353;"),
    	SOCIAL_USD_OUTLINE("&#XF352;"),
    	SOCIAL_VIMEO("&#XF245;"),
    	SOCIAL_VIMEO_OUTLINE("&#XF244;"),
    	SOCIAL_WHATSAPP("&#XF4F0;"),
    	SOCIAL_WHATSAPP_OUTLINE("&#XF4EF;"),
    	SOCIAL_WINDOWS("&#XF247;"),
    	SOCIAL_WINDOWS_OUTLINE("&#XF246;"),
    	SOCIAL_WORDPRESS("&#XF249;"),
    	SOCIAL_WORDPRESS_OUTLINE("&#XF248;"),
    	SOCIAL_YAHOO("&#XF24B;"),
    	SOCIAL_YAHOO_OUTLINE("&#XF24A;"),
    	SOCIAL_YEN("&#XF4F2;"),
    	SOCIAL_YEN_OUTLINE("&#XF4F1;"),
    	SOCIAL_YOUTUBE("&#XF24D;"),
    	SOCIAL_YOUTUBE_OUTLINE("&#XF24C;"),
    	SOUP_CAN("&#XF4F4;"),
    	SOUP_CAN_OUTLINE("&#XF4F3;"),
    	SPEAKERPHONE("&#XF2B2;"),
    	SPEEDOMETER("&#XF2B3;"),
    	SPOON("&#XF2B4;"),
    	STAR("&#XF24E;"),
    	STATS_BARS("&#XF2B5;"),
    	STEAM("&#XF30B;"),
    	STOP("&#XF24F;"),
    	THERMOMETER("&#XF2B6;"),
    	THUMBSDOWN("&#XF250;"),
    	THUMBSUP("&#XF251;"),
    	TOGGLE("&#XF355;"),
    	TOGGLE_FILLED("&#XF354;"),
    	TRANSGENDER("&#XF4F5;"),
    	TRASH_A("&#XF252;"),
    	TRASH_B("&#XF253;"),
    	TROPHY("&#XF356;"),
    	TSHIRT("&#XF4F7;"),
    	TSHIRT_OUTLINE("&#XF4F6;"),
    	UMBRELLA("&#XF2B7;"),
    	UNIVERSITY("&#XF357;"),
    	UNLOCKED("&#XF254;"),
    	UPLOAD("&#XF255;"),
    	USB("&#XF2B8;"),
    	VIDEOCAMERA("&#XF256;"),
    	VOLUME_HIGH("&#XF257;"),
    	VOLUME_LOW("&#XF258;"),
    	VOLUME_MEDIUM("&#XF259;"),
    	VOLUME_MUTE("&#XF25A;"),
    	WAND("&#XF358;"),
    	WATERDROP("&#XF25B;"),
    	WIFI("&#XF25C;"),
    	WINEGLASS("&#XF2B9;"),
    	WOMAN("&#XF25D;"),
    	WRENCH("&#XF2BA;"),
    	XBOX("&#XF30C;");
        private final String id;

        private Icon(String id) {
            this.id = id;
        }

        @Override
        public String toString() {
            return variant();
        }

        /**
         * Gets the character entity used for this {@link Icon}.
         * 
         * @return character entity
         */
        public String id() {
            return id;
        }

        /**
         * Gets the stylename used for this {@link Icon}.
         * 
         * @return the icon stylename
         */
        public String stylename() {
            return "ion-" + name().replaceAll("_", "-").toLowerCase();
        }

        /**
         * Gets the icon HTML with the given {@link IconVariant}s added.
         * <p>
         * Multiple {@link IconVariant}s can be used, but all combinations do
         * not make sense.
         * </p>
         * 
         * @param variants
         * @return
         */
        public String variant(IconVariant... variants) {
            String stylenames = stylename();
            for (IconVariant v : variants) {
                stylenames += " " + v;
            }
            return "<i class=\"" + stylenames + "\"></i>";
        }

    }
}